// Auto-generated by OpenLane
module Timer_PWM_Generator(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset,
  input[1:0] TMR_SRC,
  input[1:0] TMR_MODE,
  input[31:0] TIMER_TOP,
  input[31:0] PWM_CNTA,
  input[31:0] PWM_CNTB,
  output PWM_OUTA,
  output PWM_OUTB,
  output timer_interrupt
);
endmodule
